### ISSUE TITLE
error using with external package outside of a namespace

### ISSUE THREAD

**Issue by ratmice** [avigad/qpf#1]
I'm not sure if this is lean, or perhaps the parser, I tried to use qpf in a leanpkg,
the same _tree_ which is used in the qpf example.lean, I encountered some peculiar errors.
The first thing to notice is that code in example.lean does not use a namespace, and I believe worked fine when i tried it.

The script below produces the following errors when run here,
note that it generates 2 files, one without a namespace and one with,
The one with the namespace compiles fine, but the one without seems to have some form of parsing mishap

I'm not exactly sure if this would be a lean bug (likely) or a qpf parser bug, but it seems likely if it is a lean bug the qpf is quite possibly the thing encountering it, but let me know if i should redirect this issue elsewhere.

```
#!/bin/sh
leanpkg new qpftest
cd qpftest
leanpkg add 'https://github.com/avigad/qpf.git' -- master 
echo "import data.fix.parser.equations

namespace foo
    data tree (α β : Type)
    | nil : tree
    | cons : α → (β → tree) → tree

    #check tree.nil
    #check tree.cons
end foo" > src/ns.lean
lean --make src/ns.lean
echo "import data.fix.parser.equations

    data tree (α β : Type)
    | nil : tree
    | cons : α → (β → tree) → tree

    #check tree.nil
    #check tree.cons" > src/no_ns.lean
lean --make src/no_ns.lean
```
> tree.nil : Π (α β : Type), tree α β
> tree.cons : Π (α β : Type), α → (β → tree α β) → tree α β
> no_ns.lean:1:0: error: file 'data' not found in the LEAN_PATH
> no_ns.lean:1:0: error: file 'tree' not found in the LEAN_PATH
> no_ns.lean:1:0: error: invalid import: data could not resolve import: data
> no_ns.lean:1:0: error: invalid import: tree could not resolve import: tree
> no_ns.lean:3:14: error: command expected
> no_ns.lean:7:11: error: unknown identifier 'tree.nil'
> no_ns.lean:8:11: error: unknown identifier 'tree.cons'

**Comment by cipher1024** [comment]
That is a short coming of Lean I believe which I did not anticipate properly. If you add `#print true` before `data`, it should work properly. I think the reason is that a completely different parser handles the imports and the rest of the file and the import parser does not know about user defined commands (like `data`). I'm going to see if I can make a pull request to fix that short coming in Lean 3.

**Comment by cipher1024** [comment]
Thanks for reporting it!

**Comment by digama0** [comment]
This is a known issue with the lean 3 parser. Lean doesn't know that the imports are over until it sees a command keyword, but it won't know that `data` is a command keyword until it finishes the imports. You can resolve the problem by using any command at all; my preferred choice is `section end` which has no other side effects. I think the `import` command should allow `.` as a command terminator, like other declarations, but currently this is not implemented.
